/**
 * AI Provider Abstraction for the AI Coding Lab.
 * Decouples the application from specific AI vendors (Gemini, OpenAI, OpenRouter).
 */

export interface AIProvider {
  name: string;
  isConfigured(): boolean;
  generate(prompt: string, systemPrompt?: string): Promise<string>;
}

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export interface ChatCapableProvider extends AIProvider {
  generateChat(messages: ChatMessage[], systemPrompt?: string): Promise<string>;
}

/**
 * Google Gemini — Primary AI Provider.
 * Supports single-turn generate() and multi-turn generateChat().
 */
export class GeminiProvider implements ChatCapableProvider {
  name = "Gemini";
  private apiKey: string;
  private model: string;

  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY || "";
    this.model = process.env.GEMINI_MODEL || "gemini-2.5-flash";
  }

  isConfigured(): boolean {
    return !!this.apiKey.trim();
  }

  private getCandidateModels(): string[] {
    return [
      this.model.trim(),
      "gemini-2.5-flash",
      "gemini-flash-latest",
      "gemini-2.5-flash-lite",
      "gemini-2.5-pro",
    ].filter((m, i, arr) => m && arr.indexOf(m) === i);
  }

  async generate(prompt: string, systemPrompt: string = ""): Promise<string> {
    if (!this.isConfigured()) {
      throw new Error("GEMINI_API_KEY not configured");
    }

    const candidateModels = this.getCandidateModels();
    let lastError: Error | null = null;

    for (const modelName of candidateModels) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 30000);

      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${this.apiKey}`;

        const body: any = {
          contents: [
            {
              role: "user",
              parts: [{ text: prompt }],
            },
          ],
        };

        if (systemPrompt) {
          body.systemInstruction = { parts: [{ text: systemPrompt }] };
        }

        const res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal: controller.signal,
        });

        if (!res.ok) {
          const errText = await res.text();
          const errStatus = res.status;
          console.warn(`[AI Provider: Gemini] Model ${modelName} returned HTTP ${errStatus}: ${errText.slice(0, 150)}`);
          // If 503 (overloaded) or 429 (rate limit), try next candidate
          if (errStatus === 503 || errStatus === 429) {
            lastError = new Error(`Gemini model ${modelName} temporary issue (${errStatus})`);
            continue;
          }
          throw new Error(`Gemini API error (${errStatus}): ${errText.slice(0, 200)}`);
        }

        const data = await res.json();
        const candidate = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!candidate) throw new Error("No response generated by Gemini");
        return candidate;
      } catch (err: any) {
        lastError = err;
        console.warn(`[AI Provider: Gemini] Model ${modelName} failed: ${err.message || String(err)}`);
      } finally {
        clearTimeout(timeout);
      }
    }

    throw lastError || new Error("All Gemini candidate models failed");
  }

  /**
   * Multi-turn chat using Gemini's native content format.
   * Converts ChatMessage[] to Gemini's { role: "user"|"model", parts } format.
   */
  async generateChat(messages: ChatMessage[], systemPrompt: string = ""): Promise<string> {
    if (!this.isConfigured()) {
      throw new Error("GEMINI_API_KEY not configured");
    }

    if (!messages.length) {
      throw new Error("At least one message is required");
    }

    const candidateModels = this.getCandidateModels();
    let lastError: Error | null = null;

    for (const modelName of candidateModels) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 30000);

      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${this.apiKey}`;

        // Convert to Gemini's native multi-turn format
        const contents = messages.map((m) => ({
          role: m.role === "assistant" ? "model" : "user",
          parts: [{ text: m.content }],
        }));

        const body: any = { contents };

        if (systemPrompt) {
          body.systemInstruction = { parts: [{ text: systemPrompt }] };
        }

        console.log(
          `[AI Provider: Gemini] Chat request | Model: ${modelName} | Messages: ${messages.length} | System prompt: ${systemPrompt.length} chars`
        );

        const res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
          signal: controller.signal,
        });

        if (!res.ok) {
          const errText = await res.text();
          const errStatus = res.status;
          console.warn(`[AI Provider: Gemini] Chat model ${modelName} returned HTTP ${errStatus}: ${errText.slice(0, 150)}`);
          if (errStatus === 503 || errStatus === 429) {
            lastError = new Error(`Gemini model ${modelName} temporary issue (${errStatus})`);
            continue;
          }
          throw new Error(`Gemini API error (${errStatus}): ${errText.slice(0, 200)}`);
        }

        const data = await res.json();
        const candidate = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!candidate) throw new Error("No response generated by Gemini");

        console.log(
          `[AI Provider: Gemini] Chat success | Model: ${modelName} | Response: ${candidate.length} chars`
        );

        return candidate;
      } catch (err: any) {
        lastError = err;
        console.warn(`[AI Provider: Gemini] Chat model ${modelName} failed: ${err.message || String(err)}`);
      } finally {
        clearTimeout(timeout);
      }
    }

    throw lastError || new Error("All Gemini candidate models failed");
  }
}

export class OpenAIProvider implements AIProvider {
  name = "OpenAI";
  private apiKey: string;

  constructor() {
    this.apiKey = process.env.OPENAI_API_KEY || "";
  }

  isConfigured(): boolean {
    return !!this.apiKey.trim();
  }

  async generate(prompt: string, systemPrompt: string = ""): Promise<string> {
    if (!this.isConfigured()) {
      throw new Error("OPENAI_API_KEY not configured");
    }

    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          ...(systemPrompt ? [{ role: "system", content: systemPrompt }] : []),
          { role: "user", content: prompt },
        ],
        temperature: 0.3,
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`OpenAI API error (${res.status}): ${errText.slice(0, 150)}`);
    }

    const data = await res.json();
    const choice = data.choices?.[0]?.message?.content;
    if (!choice) throw new Error("No response generated by OpenAI");
    return choice;
  }
}

/**
 * Fallback when no AI provider is configured.
 * Does NOT pretend to be an AI — returns a clear configuration error.
 */
export class HeuristicAIProvider implements AIProvider {
  name = "Offline Backend Tutor";

  isConfigured(): boolean {
    return true;
  }

  async generate(_prompt: string): Promise<string> {
    throw new Error(
      "No AI provider is configured. Please add GEMINI_API_KEY to your backend/.env file to enable the AI Coding Lab assistant."
    );
  }
}

export class OpenRouterProvider implements AIProvider {
  name = "OpenRouter";
  private apiKey: string;
  private primaryModel: string;

  constructor() {
    this.apiKey = process.env.OPENROUTER_API_KEY || "";
    this.primaryModel = process.env.OPENROUTER_MODEL || "z-ai/glm-5.2:free";
  }

  isConfigured(): boolean {
    return !!this.apiKey.trim();
  }

  private async requestModel(modelName: string, prompt: string, systemPrompt: string): Promise<string> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 25000);

    try {
      console.log(`[AI Provider: OpenRouter] Requesting model: ${modelName} | Prompt length: ${prompt.length} chars`);

      const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.apiKey}`,
          "HTTP-Referer": process.env.CLIENT_URL || "http://localhost:3000",
          "X-Title": "Backend Academy AI Coding Lab",
        },
        body: JSON.stringify({
          model: modelName,
          messages: [
            ...(systemPrompt ? [{ role: "system", content: systemPrompt }] : []),
            { role: "user", content: prompt },
          ],
          temperature: 0.3,
          max_tokens: 4096,
        }),
        signal: controller.signal,
      });

      if (!res.ok) {
        const errText = await res.text();
        console.warn(`[AI Provider: OpenRouter] Model ${modelName} HTTP ${res.status}: ${errText.slice(0, 150)}`);
        throw new Error(`OpenRouter HTTP ${res.status}: ${errText.slice(0, 150)}`);
      }

      const data: any = await res.json();
      const choice = data.choices?.[0]?.message;
      const text = choice?.content || choice?.reasoning;

      if (!text || typeof text !== "string" || !text.trim()) {
        const apiErr = data.error?.message || "Empty content and reasoning in response";
        console.warn(`[AI Provider: OpenRouter] Model ${modelName} returned no text: ${apiErr}`);
        throw new Error(`OpenRouter returned empty response: ${apiErr}`);
      }

      console.log(`[AI Provider: OpenRouter] Success with ${modelName} | Generated length: ${text.length} chars`);
      return text.trim();
    } finally {
      clearTimeout(timeout);
    }
  }

  async generate(prompt: string, systemPrompt: string = ""): Promise<string> {
    if (!this.isConfigured()) {
      throw new Error("OPENROUTER_API_KEY not configured");
    }

    const candidateModels = [
      this.primaryModel.trim(),
      "cohere/north-mini-code:free",
      "liquid/lfm-2.5-2.6b:free",
      "inclusionai/ling-3.0-flash-fin:free",
    ].filter((m, i, arr) => m && arr.indexOf(m) === i);

    let lastError: Error | null = null;
    for (const model of candidateModels) {
      try {
        return await this.requestModel(model, prompt, systemPrompt);
      } catch (err: any) {
        lastError = err;
        console.warn(`[AI Provider: OpenRouter] Candidate ${model} failed, attempting next candidate...`);
      }
    }

    throw lastError || new Error("All OpenRouter candidate models failed");
  }
}

/**
 * Returns the best available AI provider.
 * Priority: Gemini → OpenRouter → OpenAI → HeuristicAIProvider (error-only fallback).
 */
export function getAIProvider(): AIProvider {
  const gemini = new GeminiProvider();
  if (gemini.isConfigured()) {
    console.log(`[AI Provider] Selected Gemini (Model: ${process.env.GEMINI_MODEL || "gemini-2.5-flash"})`);
    return gemini;
  }

  const openrouter = new OpenRouterProvider();
  if (openrouter.isConfigured()) {
    console.log(`[AI Provider] Selected OpenRouter (Model: ${process.env.OPENROUTER_MODEL || "default"})`);
    return openrouter;
  }

  const openai = new OpenAIProvider();
  if (openai.isConfigured()) {
    console.log("[AI Provider] Selected OpenAI");
    return openai;
  }

  console.warn("[AI Provider] No external API configured. AI assistant will return errors until a provider is configured.");
  return new HeuristicAIProvider();
}

/**
 * Returns a chat-capable provider (GeminiProvider) for multi-turn conversations.
 * Falls back to single-turn generate() wrapped in chat format if no chat provider is available.
 */
export function getChatProvider(): ChatCapableProvider {
  const gemini = new GeminiProvider();
  if (gemini.isConfigured()) {
    console.log(`[AI Provider] Selected Gemini for chat (Model: ${process.env.GEMINI_MODEL || "gemini-2.5-flash"})`);
    return gemini;
  }

  throw new Error(
    "Multi-turn chat requires Google Gemini. Please add GEMINI_API_KEY to your backend/.env file."
  );
}
